---
- name: Gathering data about IOS devices
  hosts: all

  tasks:
    - name: Gather legacy and resource facts
      cisco.ios.ios_facts:
        gather_subset: all
#        gather_network_resources: all
      register: routerData

    - name: show debug
      debug: 
        var: routerData
    
    - name: copy files to output folder
      ansible.builtin.copy: 
        content="{{ routerData | to_nice_json }}" dest="../output/{{inventory_hostname}}_iosfacts.json"