---
- name: default config to apply
  hosts: device_roles_lab-router

  tasks:
  - name: Default config
    include_tasks: '{{ defaultconfigtasks }}'
    loop:
      - ../tasks/ntpconfig.yml
      - ../tasks/interfacesettings.yml
      - ../tasks/l3interface.yml
      - ../tasks/copyrunstart.yml
    loop_control:
      loop_var: defaultconfigtasks 
