---
- name: Change setting for an interface
  cisco.ios.ios_interfaces:
    config:
    - name: "{{ interface.interface_id }}"
      description: Configured and Merged by Ansible Network
      enabled: true
  loop: "{{ interfaces_info }}"
  loop_control:
    loop_var: interface
  when: interfaces_info is defined