---
- name: Assign an ip address to an interface
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ interface.interface_id }}"
        ipv4:
          - address: "{{ interface.interface_ip }}"
  loop: "{{ interfaces_info }}"
  loop_control:
    loop_var: interface
  when: interfaces_info is defined
