---
- name: default config to apply
  hosts: device_roles_lab-router

  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l3_interfaces:
        config:
        - name: "{{ interface_id }}"
          ipv4:
          - address: "{{ interface_ip }}"