---
plugin: netbox
api_endpoint: http://angell-netbox:8000/
token: 
validate_cert: false
config_context: false
interfaces: yes
group_by:
  - device_roles
query_filters:
  - role: lab-router
  - role: lab-switch
compose:
  ansible_network_os: platform.slug
  ansible_connection: custom_fields.ansible_connection_type
  ansible_user: custom_fields.ansible_uname
  ansible_password: custom_fields.password
  
  